local:
  dialect: postgres
  datasource: host=db dbname=mission_service user=root password=password sslmode=disable
  dir: infrastructure/db/migrations
  table: migrations

development:
  dialect: postgres
  datasource: host=${DB_HOST} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
  dir: infrastructure/db/migrations
  table: migrations

production:
  dialect: postgres
  datasource: host=${DB_HOST} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
  dir: infrastructure/db/migrations
  table: migrations