version: "3.9"

services:
  api:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - .:/mission_service
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - "db"

  db:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=mission_service
    ports:
      - "5433:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data

volumes:
  psql_data:
