name: lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.3"
