// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CoinCountMissions           string
	GetItemMissions             string
	Items                       string
	LoginMissions               string
	MissionReleases             string
	MissionRewardCoins          string
	MissionRewardItems          string
	Missions                    string
	MonsterKillCountMissions    string
	MonsterKillMissions         string
	MonsterLevelUpCountMissions string
	MonsterLevelUpMissions      string
	Monsters                    string
	UserItems                   string
	UserMissionProgresses       string
	UserMissions                string
	UserMonsters                string
	Users                       string
}{
	CoinCountMissions:           "coin_count_missions",
	GetItemMissions:             "get_item_missions",
	Items:                       "items",
	LoginMissions:               "login_missions",
	MissionReleases:             "mission_releases",
	MissionRewardCoins:          "mission_reward_coins",
	MissionRewardItems:          "mission_reward_items",
	Missions:                    "missions",
	MonsterKillCountMissions:    "monster_kill_count_missions",
	MonsterKillMissions:         "monster_kill_missions",
	MonsterLevelUpCountMissions: "monster_level_up_count_missions",
	MonsterLevelUpMissions:      "monster_level_up_missions",
	Monsters:                    "monsters",
	UserItems:                   "user_items",
	UserMissionProgresses:       "user_mission_progresses",
	UserMissions:                "user_missions",
	UserMonsters:                "user_monsters",
	Users:                       "users",
}
