// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MissionRewardItem is an object representing the database table.
type MissionRewardItem struct {
	ID int64 `boil:"id" json:"id" toml:"id" yaml:"id"`
	// ミッションID
	MissionID int64 `boil:"mission_id" json:"mission_id" toml:"mission_id" yaml:"mission_id"`
	// 付与するアイテムID
	ItemID int64 `boil:"item_id" json:"item_id" toml:"item_id" yaml:"item_id"`
	// 付与するアイテムの個数
	ItemCount int64     `boil:"item_count" json:"item_count" toml:"item_count" yaml:"item_count"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *missionRewardItemR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L missionRewardItemL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MissionRewardItemColumns = struct {
	ID        string
	MissionID string
	ItemID    string
	ItemCount string
	UpdatedAt string
	CreatedAt string
}{
	ID:        "id",
	MissionID: "mission_id",
	ItemID:    "item_id",
	ItemCount: "item_count",
	UpdatedAt: "updated_at",
	CreatedAt: "created_at",
}

var MissionRewardItemTableColumns = struct {
	ID        string
	MissionID string
	ItemID    string
	ItemCount string
	UpdatedAt string
	CreatedAt string
}{
	ID:        "mission_reward_items.id",
	MissionID: "mission_reward_items.mission_id",
	ItemID:    "mission_reward_items.item_id",
	ItemCount: "mission_reward_items.item_count",
	UpdatedAt: "mission_reward_items.updated_at",
	CreatedAt: "mission_reward_items.created_at",
}

// Generated where

var MissionRewardItemWhere = struct {
	ID        whereHelperint64
	MissionID whereHelperint64
	ItemID    whereHelperint64
	ItemCount whereHelperint64
	UpdatedAt whereHelpertime_Time
	CreatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "\"mission_reward_items\".\"id\""},
	MissionID: whereHelperint64{field: "\"mission_reward_items\".\"mission_id\""},
	ItemID:    whereHelperint64{field: "\"mission_reward_items\".\"item_id\""},
	ItemCount: whereHelperint64{field: "\"mission_reward_items\".\"item_count\""},
	UpdatedAt: whereHelpertime_Time{field: "\"mission_reward_items\".\"updated_at\""},
	CreatedAt: whereHelpertime_Time{field: "\"mission_reward_items\".\"created_at\""},
}

// MissionRewardItemRels is where relationship names are stored.
var MissionRewardItemRels = struct {
	Item    string
	Mission string
}{
	Item:    "Item",
	Mission: "Mission",
}

// missionRewardItemR is where relationships are stored.
type missionRewardItemR struct {
	Item    *Item    `boil:"Item" json:"Item" toml:"Item" yaml:"Item"`
	Mission *Mission `boil:"Mission" json:"Mission" toml:"Mission" yaml:"Mission"`
}

// NewStruct creates a new relationship struct
func (*missionRewardItemR) NewStruct() *missionRewardItemR {
	return &missionRewardItemR{}
}

func (r *missionRewardItemR) GetItem() *Item {
	if r == nil {
		return nil
	}
	return r.Item
}

func (r *missionRewardItemR) GetMission() *Mission {
	if r == nil {
		return nil
	}
	return r.Mission
}

// missionRewardItemL is where Load methods for each relationship are stored.
type missionRewardItemL struct{}

var (
	missionRewardItemAllColumns            = []string{"id", "mission_id", "item_id", "item_count", "updated_at", "created_at"}
	missionRewardItemColumnsWithoutDefault = []string{"mission_id", "item_id", "item_count"}
	missionRewardItemColumnsWithDefault    = []string{"id", "updated_at", "created_at"}
	missionRewardItemPrimaryKeyColumns     = []string{"id"}
	missionRewardItemGeneratedColumns      = []string{}
)

type (
	// MissionRewardItemSlice is an alias for a slice of pointers to MissionRewardItem.
	// This should almost always be used instead of []MissionRewardItem.
	MissionRewardItemSlice []*MissionRewardItem
	// MissionRewardItemHook is the signature for custom MissionRewardItem hook methods
	MissionRewardItemHook func(context.Context, boil.ContextExecutor, *MissionRewardItem) error

	missionRewardItemQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	missionRewardItemType                 = reflect.TypeOf(&MissionRewardItem{})
	missionRewardItemMapping              = queries.MakeStructMapping(missionRewardItemType)
	missionRewardItemPrimaryKeyMapping, _ = queries.BindMapping(missionRewardItemType, missionRewardItemMapping, missionRewardItemPrimaryKeyColumns)
	missionRewardItemInsertCacheMut       sync.RWMutex
	missionRewardItemInsertCache          = make(map[string]insertCache)
	missionRewardItemUpdateCacheMut       sync.RWMutex
	missionRewardItemUpdateCache          = make(map[string]updateCache)
	missionRewardItemUpsertCacheMut       sync.RWMutex
	missionRewardItemUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var missionRewardItemAfterSelectHooks []MissionRewardItemHook

var missionRewardItemBeforeInsertHooks []MissionRewardItemHook
var missionRewardItemAfterInsertHooks []MissionRewardItemHook

var missionRewardItemBeforeUpdateHooks []MissionRewardItemHook
var missionRewardItemAfterUpdateHooks []MissionRewardItemHook

var missionRewardItemBeforeDeleteHooks []MissionRewardItemHook
var missionRewardItemAfterDeleteHooks []MissionRewardItemHook

var missionRewardItemBeforeUpsertHooks []MissionRewardItemHook
var missionRewardItemAfterUpsertHooks []MissionRewardItemHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MissionRewardItem) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range missionRewardItemAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MissionRewardItem) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range missionRewardItemBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MissionRewardItem) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range missionRewardItemAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MissionRewardItem) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range missionRewardItemBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MissionRewardItem) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range missionRewardItemAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MissionRewardItem) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range missionRewardItemBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MissionRewardItem) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range missionRewardItemAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MissionRewardItem) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range missionRewardItemBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MissionRewardItem) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range missionRewardItemAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMissionRewardItemHook registers your hook function for all future operations.
func AddMissionRewardItemHook(hookPoint boil.HookPoint, missionRewardItemHook MissionRewardItemHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		missionRewardItemAfterSelectHooks = append(missionRewardItemAfterSelectHooks, missionRewardItemHook)
	case boil.BeforeInsertHook:
		missionRewardItemBeforeInsertHooks = append(missionRewardItemBeforeInsertHooks, missionRewardItemHook)
	case boil.AfterInsertHook:
		missionRewardItemAfterInsertHooks = append(missionRewardItemAfterInsertHooks, missionRewardItemHook)
	case boil.BeforeUpdateHook:
		missionRewardItemBeforeUpdateHooks = append(missionRewardItemBeforeUpdateHooks, missionRewardItemHook)
	case boil.AfterUpdateHook:
		missionRewardItemAfterUpdateHooks = append(missionRewardItemAfterUpdateHooks, missionRewardItemHook)
	case boil.BeforeDeleteHook:
		missionRewardItemBeforeDeleteHooks = append(missionRewardItemBeforeDeleteHooks, missionRewardItemHook)
	case boil.AfterDeleteHook:
		missionRewardItemAfterDeleteHooks = append(missionRewardItemAfterDeleteHooks, missionRewardItemHook)
	case boil.BeforeUpsertHook:
		missionRewardItemBeforeUpsertHooks = append(missionRewardItemBeforeUpsertHooks, missionRewardItemHook)
	case boil.AfterUpsertHook:
		missionRewardItemAfterUpsertHooks = append(missionRewardItemAfterUpsertHooks, missionRewardItemHook)
	}
}

// One returns a single missionRewardItem record from the query.
func (q missionRewardItemQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MissionRewardItem, error) {
	o := &MissionRewardItem{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for mission_reward_items")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MissionRewardItem records from the query.
func (q missionRewardItemQuery) All(ctx context.Context, exec boil.ContextExecutor) (MissionRewardItemSlice, error) {
	var o []*MissionRewardItem

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MissionRewardItem slice")
	}

	if len(missionRewardItemAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MissionRewardItem records in the query.
func (q missionRewardItemQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count mission_reward_items rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q missionRewardItemQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if mission_reward_items exists")
	}

	return count > 0, nil
}

// Item pointed to by the foreign key.
func (o *MissionRewardItem) Item(mods ...qm.QueryMod) itemQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ItemID),
	}

	queryMods = append(queryMods, mods...)

	return Items(queryMods...)
}

// Mission pointed to by the foreign key.
func (o *MissionRewardItem) Mission(mods ...qm.QueryMod) missionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MissionID),
	}

	queryMods = append(queryMods, mods...)

	return Missions(queryMods...)
}

// LoadItem allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (missionRewardItemL) LoadItem(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMissionRewardItem interface{}, mods queries.Applicator) error {
	var slice []*MissionRewardItem
	var object *MissionRewardItem

	if singular {
		var ok bool
		object, ok = maybeMissionRewardItem.(*MissionRewardItem)
		if !ok {
			object = new(MissionRewardItem)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMissionRewardItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMissionRewardItem))
			}
		}
	} else {
		s, ok := maybeMissionRewardItem.(*[]*MissionRewardItem)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMissionRewardItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMissionRewardItem))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &missionRewardItemR{}
		}
		args = append(args, object.ItemID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &missionRewardItemR{}
			}

			for _, a := range args {
				if a == obj.ItemID {
					continue Outer
				}
			}

			args = append(args, obj.ItemID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`items`),
		qm.WhereIn(`items.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Item")
	}

	var resultSlice []*Item
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Item")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for items")
	}

	if len(itemAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Item = foreign
		if foreign.R == nil {
			foreign.R = &itemR{}
		}
		foreign.R.MissionRewardItems = append(foreign.R.MissionRewardItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ItemID == foreign.ID {
				local.R.Item = foreign
				if foreign.R == nil {
					foreign.R = &itemR{}
				}
				foreign.R.MissionRewardItems = append(foreign.R.MissionRewardItems, local)
				break
			}
		}
	}

	return nil
}

// LoadMission allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (missionRewardItemL) LoadMission(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMissionRewardItem interface{}, mods queries.Applicator) error {
	var slice []*MissionRewardItem
	var object *MissionRewardItem

	if singular {
		var ok bool
		object, ok = maybeMissionRewardItem.(*MissionRewardItem)
		if !ok {
			object = new(MissionRewardItem)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMissionRewardItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMissionRewardItem))
			}
		}
	} else {
		s, ok := maybeMissionRewardItem.(*[]*MissionRewardItem)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMissionRewardItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMissionRewardItem))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &missionRewardItemR{}
		}
		args = append(args, object.MissionID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &missionRewardItemR{}
			}

			for _, a := range args {
				if a == obj.MissionID {
					continue Outer
				}
			}

			args = append(args, obj.MissionID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`missions`),
		qm.WhereIn(`missions.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Mission")
	}

	var resultSlice []*Mission
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Mission")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for missions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for missions")
	}

	if len(missionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Mission = foreign
		if foreign.R == nil {
			foreign.R = &missionR{}
		}
		foreign.R.MissionRewardItems = append(foreign.R.MissionRewardItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.MissionID == foreign.ID {
				local.R.Mission = foreign
				if foreign.R == nil {
					foreign.R = &missionR{}
				}
				foreign.R.MissionRewardItems = append(foreign.R.MissionRewardItems, local)
				break
			}
		}
	}

	return nil
}

// SetItem of the missionRewardItem to the related item.
// Sets o.R.Item to related.
// Adds o to related.R.MissionRewardItems.
func (o *MissionRewardItem) SetItem(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Item) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"mission_reward_items\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"item_id"}),
		strmangle.WhereClause("\"", "\"", 2, missionRewardItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ItemID = related.ID
	if o.R == nil {
		o.R = &missionRewardItemR{
			Item: related,
		}
	} else {
		o.R.Item = related
	}

	if related.R == nil {
		related.R = &itemR{
			MissionRewardItems: MissionRewardItemSlice{o},
		}
	} else {
		related.R.MissionRewardItems = append(related.R.MissionRewardItems, o)
	}

	return nil
}

// SetMission of the missionRewardItem to the related item.
// Sets o.R.Mission to related.
// Adds o to related.R.MissionRewardItems.
func (o *MissionRewardItem) SetMission(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Mission) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"mission_reward_items\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"mission_id"}),
		strmangle.WhereClause("\"", "\"", 2, missionRewardItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.MissionID = related.ID
	if o.R == nil {
		o.R = &missionRewardItemR{
			Mission: related,
		}
	} else {
		o.R.Mission = related
	}

	if related.R == nil {
		related.R = &missionR{
			MissionRewardItems: MissionRewardItemSlice{o},
		}
	} else {
		related.R.MissionRewardItems = append(related.R.MissionRewardItems, o)
	}

	return nil
}

// MissionRewardItems retrieves all the records using an executor.
func MissionRewardItems(mods ...qm.QueryMod) missionRewardItemQuery {
	mods = append(mods, qm.From("\"mission_reward_items\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"mission_reward_items\".*"})
	}

	return missionRewardItemQuery{q}
}

// FindMissionRewardItem retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMissionRewardItem(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*MissionRewardItem, error) {
	missionRewardItemObj := &MissionRewardItem{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"mission_reward_items\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, missionRewardItemObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from mission_reward_items")
	}

	if err = missionRewardItemObj.doAfterSelectHooks(ctx, exec); err != nil {
		return missionRewardItemObj, err
	}

	return missionRewardItemObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MissionRewardItem) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no mission_reward_items provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(missionRewardItemColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	missionRewardItemInsertCacheMut.RLock()
	cache, cached := missionRewardItemInsertCache[key]
	missionRewardItemInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			missionRewardItemAllColumns,
			missionRewardItemColumnsWithDefault,
			missionRewardItemColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(missionRewardItemType, missionRewardItemMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(missionRewardItemType, missionRewardItemMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"mission_reward_items\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"mission_reward_items\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into mission_reward_items")
	}

	if !cached {
		missionRewardItemInsertCacheMut.Lock()
		missionRewardItemInsertCache[key] = cache
		missionRewardItemInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MissionRewardItem.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MissionRewardItem) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	missionRewardItemUpdateCacheMut.RLock()
	cache, cached := missionRewardItemUpdateCache[key]
	missionRewardItemUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			missionRewardItemAllColumns,
			missionRewardItemPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update mission_reward_items, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"mission_reward_items\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, missionRewardItemPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(missionRewardItemType, missionRewardItemMapping, append(wl, missionRewardItemPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update mission_reward_items row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for mission_reward_items")
	}

	if !cached {
		missionRewardItemUpdateCacheMut.Lock()
		missionRewardItemUpdateCache[key] = cache
		missionRewardItemUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q missionRewardItemQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for mission_reward_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for mission_reward_items")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MissionRewardItemSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), missionRewardItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"mission_reward_items\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, missionRewardItemPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in missionRewardItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all missionRewardItem")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MissionRewardItem) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no mission_reward_items provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(missionRewardItemColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	missionRewardItemUpsertCacheMut.RLock()
	cache, cached := missionRewardItemUpsertCache[key]
	missionRewardItemUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			missionRewardItemAllColumns,
			missionRewardItemColumnsWithDefault,
			missionRewardItemColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			missionRewardItemAllColumns,
			missionRewardItemPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert mission_reward_items, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(missionRewardItemPrimaryKeyColumns))
			copy(conflict, missionRewardItemPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"mission_reward_items\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(missionRewardItemType, missionRewardItemMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(missionRewardItemType, missionRewardItemMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert mission_reward_items")
	}

	if !cached {
		missionRewardItemUpsertCacheMut.Lock()
		missionRewardItemUpsertCache[key] = cache
		missionRewardItemUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MissionRewardItem record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MissionRewardItem) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MissionRewardItem provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), missionRewardItemPrimaryKeyMapping)
	sql := "DELETE FROM \"mission_reward_items\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from mission_reward_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for mission_reward_items")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q missionRewardItemQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no missionRewardItemQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from mission_reward_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for mission_reward_items")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MissionRewardItemSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(missionRewardItemBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), missionRewardItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"mission_reward_items\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, missionRewardItemPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from missionRewardItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for mission_reward_items")
	}

	if len(missionRewardItemAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MissionRewardItem) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMissionRewardItem(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MissionRewardItemSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MissionRewardItemSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), missionRewardItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"mission_reward_items\".* FROM \"mission_reward_items\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, missionRewardItemPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MissionRewardItemSlice")
	}

	*o = slice

	return nil
}

// MissionRewardItemExists checks if the MissionRewardItem row exists.
func MissionRewardItemExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"mission_reward_items\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if mission_reward_items exists")
	}

	return exists, nil
}

// Exists checks if the MissionRewardItem row exists.
func (o *MissionRewardItem) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MissionRewardItemExists(ctx, exec, o.ID)
}
