// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MonsterKillMission is an object representing the database table.
type MonsterKillMission struct {
	ID int64 `boil:"id" json:"id" toml:"id" yaml:"id"`
	// ミッションID
	MissionID int64 `boil:"mission_id" json:"mission_id" toml:"mission_id" yaml:"mission_id"`
	// 対象モンスターID
	MonsterID int64     `boil:"monster_id" json:"monster_id" toml:"monster_id" yaml:"monster_id"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *monsterKillMissionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L monsterKillMissionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MonsterKillMissionColumns = struct {
	ID        string
	MissionID string
	MonsterID string
	UpdatedAt string
	CreatedAt string
}{
	ID:        "id",
	MissionID: "mission_id",
	MonsterID: "monster_id",
	UpdatedAt: "updated_at",
	CreatedAt: "created_at",
}

var MonsterKillMissionTableColumns = struct {
	ID        string
	MissionID string
	MonsterID string
	UpdatedAt string
	CreatedAt string
}{
	ID:        "monster_kill_missions.id",
	MissionID: "monster_kill_missions.mission_id",
	MonsterID: "monster_kill_missions.monster_id",
	UpdatedAt: "monster_kill_missions.updated_at",
	CreatedAt: "monster_kill_missions.created_at",
}

// Generated where

var MonsterKillMissionWhere = struct {
	ID        whereHelperint64
	MissionID whereHelperint64
	MonsterID whereHelperint64
	UpdatedAt whereHelpertime_Time
	CreatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "\"monster_kill_missions\".\"id\""},
	MissionID: whereHelperint64{field: "\"monster_kill_missions\".\"mission_id\""},
	MonsterID: whereHelperint64{field: "\"monster_kill_missions\".\"monster_id\""},
	UpdatedAt: whereHelpertime_Time{field: "\"monster_kill_missions\".\"updated_at\""},
	CreatedAt: whereHelpertime_Time{field: "\"monster_kill_missions\".\"created_at\""},
}

// MonsterKillMissionRels is where relationship names are stored.
var MonsterKillMissionRels = struct {
	Mission string
	Monster string
}{
	Mission: "Mission",
	Monster: "Monster",
}

// monsterKillMissionR is where relationships are stored.
type monsterKillMissionR struct {
	Mission *Mission `boil:"Mission" json:"Mission" toml:"Mission" yaml:"Mission"`
	Monster *Monster `boil:"Monster" json:"Monster" toml:"Monster" yaml:"Monster"`
}

// NewStruct creates a new relationship struct
func (*monsterKillMissionR) NewStruct() *monsterKillMissionR {
	return &monsterKillMissionR{}
}

func (r *monsterKillMissionR) GetMission() *Mission {
	if r == nil {
		return nil
	}
	return r.Mission
}

func (r *monsterKillMissionR) GetMonster() *Monster {
	if r == nil {
		return nil
	}
	return r.Monster
}

// monsterKillMissionL is where Load methods for each relationship are stored.
type monsterKillMissionL struct{}

var (
	monsterKillMissionAllColumns            = []string{"id", "mission_id", "monster_id", "updated_at", "created_at"}
	monsterKillMissionColumnsWithoutDefault = []string{"mission_id", "monster_id"}
	monsterKillMissionColumnsWithDefault    = []string{"id", "updated_at", "created_at"}
	monsterKillMissionPrimaryKeyColumns     = []string{"id"}
	monsterKillMissionGeneratedColumns      = []string{}
)

type (
	// MonsterKillMissionSlice is an alias for a slice of pointers to MonsterKillMission.
	// This should almost always be used instead of []MonsterKillMission.
	MonsterKillMissionSlice []*MonsterKillMission
	// MonsterKillMissionHook is the signature for custom MonsterKillMission hook methods
	MonsterKillMissionHook func(context.Context, boil.ContextExecutor, *MonsterKillMission) error

	monsterKillMissionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	monsterKillMissionType                 = reflect.TypeOf(&MonsterKillMission{})
	monsterKillMissionMapping              = queries.MakeStructMapping(monsterKillMissionType)
	monsterKillMissionPrimaryKeyMapping, _ = queries.BindMapping(monsterKillMissionType, monsterKillMissionMapping, monsterKillMissionPrimaryKeyColumns)
	monsterKillMissionInsertCacheMut       sync.RWMutex
	monsterKillMissionInsertCache          = make(map[string]insertCache)
	monsterKillMissionUpdateCacheMut       sync.RWMutex
	monsterKillMissionUpdateCache          = make(map[string]updateCache)
	monsterKillMissionUpsertCacheMut       sync.RWMutex
	monsterKillMissionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var monsterKillMissionAfterSelectHooks []MonsterKillMissionHook

var monsterKillMissionBeforeInsertHooks []MonsterKillMissionHook
var monsterKillMissionAfterInsertHooks []MonsterKillMissionHook

var monsterKillMissionBeforeUpdateHooks []MonsterKillMissionHook
var monsterKillMissionAfterUpdateHooks []MonsterKillMissionHook

var monsterKillMissionBeforeDeleteHooks []MonsterKillMissionHook
var monsterKillMissionAfterDeleteHooks []MonsterKillMissionHook

var monsterKillMissionBeforeUpsertHooks []MonsterKillMissionHook
var monsterKillMissionAfterUpsertHooks []MonsterKillMissionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MonsterKillMission) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monsterKillMissionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MonsterKillMission) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monsterKillMissionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MonsterKillMission) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monsterKillMissionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MonsterKillMission) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monsterKillMissionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MonsterKillMission) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monsterKillMissionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MonsterKillMission) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monsterKillMissionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MonsterKillMission) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monsterKillMissionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MonsterKillMission) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monsterKillMissionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MonsterKillMission) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monsterKillMissionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMonsterKillMissionHook registers your hook function for all future operations.
func AddMonsterKillMissionHook(hookPoint boil.HookPoint, monsterKillMissionHook MonsterKillMissionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		monsterKillMissionAfterSelectHooks = append(monsterKillMissionAfterSelectHooks, monsterKillMissionHook)
	case boil.BeforeInsertHook:
		monsterKillMissionBeforeInsertHooks = append(monsterKillMissionBeforeInsertHooks, monsterKillMissionHook)
	case boil.AfterInsertHook:
		monsterKillMissionAfterInsertHooks = append(monsterKillMissionAfterInsertHooks, monsterKillMissionHook)
	case boil.BeforeUpdateHook:
		monsterKillMissionBeforeUpdateHooks = append(monsterKillMissionBeforeUpdateHooks, monsterKillMissionHook)
	case boil.AfterUpdateHook:
		monsterKillMissionAfterUpdateHooks = append(monsterKillMissionAfterUpdateHooks, monsterKillMissionHook)
	case boil.BeforeDeleteHook:
		monsterKillMissionBeforeDeleteHooks = append(monsterKillMissionBeforeDeleteHooks, monsterKillMissionHook)
	case boil.AfterDeleteHook:
		monsterKillMissionAfterDeleteHooks = append(monsterKillMissionAfterDeleteHooks, monsterKillMissionHook)
	case boil.BeforeUpsertHook:
		monsterKillMissionBeforeUpsertHooks = append(monsterKillMissionBeforeUpsertHooks, monsterKillMissionHook)
	case boil.AfterUpsertHook:
		monsterKillMissionAfterUpsertHooks = append(monsterKillMissionAfterUpsertHooks, monsterKillMissionHook)
	}
}

// One returns a single monsterKillMission record from the query.
func (q monsterKillMissionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MonsterKillMission, error) {
	o := &MonsterKillMission{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for monster_kill_missions")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MonsterKillMission records from the query.
func (q monsterKillMissionQuery) All(ctx context.Context, exec boil.ContextExecutor) (MonsterKillMissionSlice, error) {
	var o []*MonsterKillMission

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MonsterKillMission slice")
	}

	if len(monsterKillMissionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MonsterKillMission records in the query.
func (q monsterKillMissionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count monster_kill_missions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q monsterKillMissionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if monster_kill_missions exists")
	}

	return count > 0, nil
}

// Mission pointed to by the foreign key.
func (o *MonsterKillMission) Mission(mods ...qm.QueryMod) missionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MissionID),
	}

	queryMods = append(queryMods, mods...)

	return Missions(queryMods...)
}

// Monster pointed to by the foreign key.
func (o *MonsterKillMission) Monster(mods ...qm.QueryMod) monsterQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MonsterID),
	}

	queryMods = append(queryMods, mods...)

	return Monsters(queryMods...)
}

// LoadMission allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (monsterKillMissionL) LoadMission(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMonsterKillMission interface{}, mods queries.Applicator) error {
	var slice []*MonsterKillMission
	var object *MonsterKillMission

	if singular {
		var ok bool
		object, ok = maybeMonsterKillMission.(*MonsterKillMission)
		if !ok {
			object = new(MonsterKillMission)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMonsterKillMission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMonsterKillMission))
			}
		}
	} else {
		s, ok := maybeMonsterKillMission.(*[]*MonsterKillMission)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMonsterKillMission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMonsterKillMission))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &monsterKillMissionR{}
		}
		args = append(args, object.MissionID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &monsterKillMissionR{}
			}

			for _, a := range args {
				if a == obj.MissionID {
					continue Outer
				}
			}

			args = append(args, obj.MissionID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`missions`),
		qm.WhereIn(`missions.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Mission")
	}

	var resultSlice []*Mission
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Mission")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for missions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for missions")
	}

	if len(missionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Mission = foreign
		if foreign.R == nil {
			foreign.R = &missionR{}
		}
		foreign.R.MonsterKillMission = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.MissionID == foreign.ID {
				local.R.Mission = foreign
				if foreign.R == nil {
					foreign.R = &missionR{}
				}
				foreign.R.MonsterKillMission = local
				break
			}
		}
	}

	return nil
}

// LoadMonster allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (monsterKillMissionL) LoadMonster(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMonsterKillMission interface{}, mods queries.Applicator) error {
	var slice []*MonsterKillMission
	var object *MonsterKillMission

	if singular {
		var ok bool
		object, ok = maybeMonsterKillMission.(*MonsterKillMission)
		if !ok {
			object = new(MonsterKillMission)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMonsterKillMission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMonsterKillMission))
			}
		}
	} else {
		s, ok := maybeMonsterKillMission.(*[]*MonsterKillMission)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMonsterKillMission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMonsterKillMission))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &monsterKillMissionR{}
		}
		args = append(args, object.MonsterID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &monsterKillMissionR{}
			}

			for _, a := range args {
				if a == obj.MonsterID {
					continue Outer
				}
			}

			args = append(args, obj.MonsterID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`monsters`),
		qm.WhereIn(`monsters.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Monster")
	}

	var resultSlice []*Monster
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Monster")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for monsters")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for monsters")
	}

	if len(monsterAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Monster = foreign
		if foreign.R == nil {
			foreign.R = &monsterR{}
		}
		foreign.R.MonsterKillMissions = append(foreign.R.MonsterKillMissions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.MonsterID == foreign.ID {
				local.R.Monster = foreign
				if foreign.R == nil {
					foreign.R = &monsterR{}
				}
				foreign.R.MonsterKillMissions = append(foreign.R.MonsterKillMissions, local)
				break
			}
		}
	}

	return nil
}

// SetMission of the monsterKillMission to the related item.
// Sets o.R.Mission to related.
// Adds o to related.R.MonsterKillMission.
func (o *MonsterKillMission) SetMission(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Mission) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"monster_kill_missions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"mission_id"}),
		strmangle.WhereClause("\"", "\"", 2, monsterKillMissionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.MissionID = related.ID
	if o.R == nil {
		o.R = &monsterKillMissionR{
			Mission: related,
		}
	} else {
		o.R.Mission = related
	}

	if related.R == nil {
		related.R = &missionR{
			MonsterKillMission: o,
		}
	} else {
		related.R.MonsterKillMission = o
	}

	return nil
}

// SetMonster of the monsterKillMission to the related item.
// Sets o.R.Monster to related.
// Adds o to related.R.MonsterKillMissions.
func (o *MonsterKillMission) SetMonster(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Monster) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"monster_kill_missions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"monster_id"}),
		strmangle.WhereClause("\"", "\"", 2, monsterKillMissionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.MonsterID = related.ID
	if o.R == nil {
		o.R = &monsterKillMissionR{
			Monster: related,
		}
	} else {
		o.R.Monster = related
	}

	if related.R == nil {
		related.R = &monsterR{
			MonsterKillMissions: MonsterKillMissionSlice{o},
		}
	} else {
		related.R.MonsterKillMissions = append(related.R.MonsterKillMissions, o)
	}

	return nil
}

// MonsterKillMissions retrieves all the records using an executor.
func MonsterKillMissions(mods ...qm.QueryMod) monsterKillMissionQuery {
	mods = append(mods, qm.From("\"monster_kill_missions\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"monster_kill_missions\".*"})
	}

	return monsterKillMissionQuery{q}
}

// FindMonsterKillMission retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMonsterKillMission(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*MonsterKillMission, error) {
	monsterKillMissionObj := &MonsterKillMission{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"monster_kill_missions\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, monsterKillMissionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from monster_kill_missions")
	}

	if err = monsterKillMissionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return monsterKillMissionObj, err
	}

	return monsterKillMissionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MonsterKillMission) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no monster_kill_missions provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(monsterKillMissionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	monsterKillMissionInsertCacheMut.RLock()
	cache, cached := monsterKillMissionInsertCache[key]
	monsterKillMissionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			monsterKillMissionAllColumns,
			monsterKillMissionColumnsWithDefault,
			monsterKillMissionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(monsterKillMissionType, monsterKillMissionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(monsterKillMissionType, monsterKillMissionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"monster_kill_missions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"monster_kill_missions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into monster_kill_missions")
	}

	if !cached {
		monsterKillMissionInsertCacheMut.Lock()
		monsterKillMissionInsertCache[key] = cache
		monsterKillMissionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MonsterKillMission.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MonsterKillMission) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	monsterKillMissionUpdateCacheMut.RLock()
	cache, cached := monsterKillMissionUpdateCache[key]
	monsterKillMissionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			monsterKillMissionAllColumns,
			monsterKillMissionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update monster_kill_missions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"monster_kill_missions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, monsterKillMissionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(monsterKillMissionType, monsterKillMissionMapping, append(wl, monsterKillMissionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update monster_kill_missions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for monster_kill_missions")
	}

	if !cached {
		monsterKillMissionUpdateCacheMut.Lock()
		monsterKillMissionUpdateCache[key] = cache
		monsterKillMissionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q monsterKillMissionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for monster_kill_missions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for monster_kill_missions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MonsterKillMissionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), monsterKillMissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"monster_kill_missions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, monsterKillMissionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in monsterKillMission slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all monsterKillMission")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MonsterKillMission) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no monster_kill_missions provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(monsterKillMissionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	monsterKillMissionUpsertCacheMut.RLock()
	cache, cached := monsterKillMissionUpsertCache[key]
	monsterKillMissionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			monsterKillMissionAllColumns,
			monsterKillMissionColumnsWithDefault,
			monsterKillMissionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			monsterKillMissionAllColumns,
			monsterKillMissionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert monster_kill_missions, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(monsterKillMissionPrimaryKeyColumns))
			copy(conflict, monsterKillMissionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"monster_kill_missions\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(monsterKillMissionType, monsterKillMissionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(monsterKillMissionType, monsterKillMissionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert monster_kill_missions")
	}

	if !cached {
		monsterKillMissionUpsertCacheMut.Lock()
		monsterKillMissionUpsertCache[key] = cache
		monsterKillMissionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MonsterKillMission record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MonsterKillMission) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MonsterKillMission provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), monsterKillMissionPrimaryKeyMapping)
	sql := "DELETE FROM \"monster_kill_missions\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from monster_kill_missions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for monster_kill_missions")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q monsterKillMissionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no monsterKillMissionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from monster_kill_missions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for monster_kill_missions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MonsterKillMissionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(monsterKillMissionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), monsterKillMissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"monster_kill_missions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, monsterKillMissionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from monsterKillMission slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for monster_kill_missions")
	}

	if len(monsterKillMissionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MonsterKillMission) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMonsterKillMission(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MonsterKillMissionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MonsterKillMissionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), monsterKillMissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"monster_kill_missions\".* FROM \"monster_kill_missions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, monsterKillMissionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MonsterKillMissionSlice")
	}

	*o = slice

	return nil
}

// MonsterKillMissionExists checks if the MonsterKillMission row exists.
func MonsterKillMissionExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"monster_kill_missions\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if monster_kill_missions exists")
	}

	return exists, nil
}

// Exists checks if the MonsterKillMission row exists.
func (o *MonsterKillMission) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MonsterKillMissionExists(ctx, exec, o.ID)
}
