// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MonstersLevelUpMission is an object representing the database table.
type MonstersLevelUpMission struct {
	ID int64 `boil:"id" json:"id" toml:"id" yaml:"id"`
	// ミッションID
	MissionID int64 `boil:"mission_id" json:"mission_id" toml:"mission_id" yaml:"mission_id"`
	// 獲得必要モンスター数
	MonsterCount int64 `boil:"monster_count" json:"monster_count" toml:"monster_count" yaml:"monster_count"`
	// 対象のレベル
	Level     int       `boil:"level" json:"level" toml:"level" yaml:"level"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *monstersLevelUpMissionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L monstersLevelUpMissionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MonstersLevelUpMissionColumns = struct {
	ID           string
	MissionID    string
	MonsterCount string
	Level        string
	UpdatedAt    string
	CreatedAt    string
}{
	ID:           "id",
	MissionID:    "mission_id",
	MonsterCount: "monster_count",
	Level:        "level",
	UpdatedAt:    "updated_at",
	CreatedAt:    "created_at",
}

var MonstersLevelUpMissionTableColumns = struct {
	ID           string
	MissionID    string
	MonsterCount string
	Level        string
	UpdatedAt    string
	CreatedAt    string
}{
	ID:           "monsters_level_up_missions.id",
	MissionID:    "monsters_level_up_missions.mission_id",
	MonsterCount: "monsters_level_up_missions.monster_count",
	Level:        "monsters_level_up_missions.level",
	UpdatedAt:    "monsters_level_up_missions.updated_at",
	CreatedAt:    "monsters_level_up_missions.created_at",
}

// Generated where

var MonstersLevelUpMissionWhere = struct {
	ID           whereHelperint64
	MissionID    whereHelperint64
	MonsterCount whereHelperint64
	Level        whereHelperint
	UpdatedAt    whereHelpertime_Time
	CreatedAt    whereHelpertime_Time
}{
	ID:           whereHelperint64{field: "\"monsters_level_up_missions\".\"id\""},
	MissionID:    whereHelperint64{field: "\"monsters_level_up_missions\".\"mission_id\""},
	MonsterCount: whereHelperint64{field: "\"monsters_level_up_missions\".\"monster_count\""},
	Level:        whereHelperint{field: "\"monsters_level_up_missions\".\"level\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"monsters_level_up_missions\".\"updated_at\""},
	CreatedAt:    whereHelpertime_Time{field: "\"monsters_level_up_missions\".\"created_at\""},
}

// MonstersLevelUpMissionRels is where relationship names are stored.
var MonstersLevelUpMissionRels = struct {
	Mission string
}{
	Mission: "Mission",
}

// monstersLevelUpMissionR is where relationships are stored.
type monstersLevelUpMissionR struct {
	Mission *Mission `boil:"Mission" json:"Mission" toml:"Mission" yaml:"Mission"`
}

// NewStruct creates a new relationship struct
func (*monstersLevelUpMissionR) NewStruct() *monstersLevelUpMissionR {
	return &monstersLevelUpMissionR{}
}

func (r *monstersLevelUpMissionR) GetMission() *Mission {
	if r == nil {
		return nil
	}
	return r.Mission
}

// monstersLevelUpMissionL is where Load methods for each relationship are stored.
type monstersLevelUpMissionL struct{}

var (
	monstersLevelUpMissionAllColumns            = []string{"id", "mission_id", "monster_count", "level", "updated_at", "created_at"}
	monstersLevelUpMissionColumnsWithoutDefault = []string{"mission_id", "monster_count", "level"}
	monstersLevelUpMissionColumnsWithDefault    = []string{"id", "updated_at", "created_at"}
	monstersLevelUpMissionPrimaryKeyColumns     = []string{"id"}
	monstersLevelUpMissionGeneratedColumns      = []string{}
)

type (
	// MonstersLevelUpMissionSlice is an alias for a slice of pointers to MonstersLevelUpMission.
	// This should almost always be used instead of []MonstersLevelUpMission.
	MonstersLevelUpMissionSlice []*MonstersLevelUpMission
	// MonstersLevelUpMissionHook is the signature for custom MonstersLevelUpMission hook methods
	MonstersLevelUpMissionHook func(context.Context, boil.ContextExecutor, *MonstersLevelUpMission) error

	monstersLevelUpMissionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	monstersLevelUpMissionType                 = reflect.TypeOf(&MonstersLevelUpMission{})
	monstersLevelUpMissionMapping              = queries.MakeStructMapping(monstersLevelUpMissionType)
	monstersLevelUpMissionPrimaryKeyMapping, _ = queries.BindMapping(monstersLevelUpMissionType, monstersLevelUpMissionMapping, monstersLevelUpMissionPrimaryKeyColumns)
	monstersLevelUpMissionInsertCacheMut       sync.RWMutex
	monstersLevelUpMissionInsertCache          = make(map[string]insertCache)
	monstersLevelUpMissionUpdateCacheMut       sync.RWMutex
	monstersLevelUpMissionUpdateCache          = make(map[string]updateCache)
	monstersLevelUpMissionUpsertCacheMut       sync.RWMutex
	monstersLevelUpMissionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var monstersLevelUpMissionAfterSelectHooks []MonstersLevelUpMissionHook

var monstersLevelUpMissionBeforeInsertHooks []MonstersLevelUpMissionHook
var monstersLevelUpMissionAfterInsertHooks []MonstersLevelUpMissionHook

var monstersLevelUpMissionBeforeUpdateHooks []MonstersLevelUpMissionHook
var monstersLevelUpMissionAfterUpdateHooks []MonstersLevelUpMissionHook

var monstersLevelUpMissionBeforeDeleteHooks []MonstersLevelUpMissionHook
var monstersLevelUpMissionAfterDeleteHooks []MonstersLevelUpMissionHook

var monstersLevelUpMissionBeforeUpsertHooks []MonstersLevelUpMissionHook
var monstersLevelUpMissionAfterUpsertHooks []MonstersLevelUpMissionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MonstersLevelUpMission) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monstersLevelUpMissionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MonstersLevelUpMission) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monstersLevelUpMissionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MonstersLevelUpMission) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monstersLevelUpMissionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MonstersLevelUpMission) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monstersLevelUpMissionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MonstersLevelUpMission) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monstersLevelUpMissionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MonstersLevelUpMission) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monstersLevelUpMissionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MonstersLevelUpMission) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monstersLevelUpMissionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MonstersLevelUpMission) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monstersLevelUpMissionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MonstersLevelUpMission) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range monstersLevelUpMissionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMonstersLevelUpMissionHook registers your hook function for all future operations.
func AddMonstersLevelUpMissionHook(hookPoint boil.HookPoint, monstersLevelUpMissionHook MonstersLevelUpMissionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		monstersLevelUpMissionAfterSelectHooks = append(monstersLevelUpMissionAfterSelectHooks, monstersLevelUpMissionHook)
	case boil.BeforeInsertHook:
		monstersLevelUpMissionBeforeInsertHooks = append(monstersLevelUpMissionBeforeInsertHooks, monstersLevelUpMissionHook)
	case boil.AfterInsertHook:
		monstersLevelUpMissionAfterInsertHooks = append(monstersLevelUpMissionAfterInsertHooks, monstersLevelUpMissionHook)
	case boil.BeforeUpdateHook:
		monstersLevelUpMissionBeforeUpdateHooks = append(monstersLevelUpMissionBeforeUpdateHooks, monstersLevelUpMissionHook)
	case boil.AfterUpdateHook:
		monstersLevelUpMissionAfterUpdateHooks = append(monstersLevelUpMissionAfterUpdateHooks, monstersLevelUpMissionHook)
	case boil.BeforeDeleteHook:
		monstersLevelUpMissionBeforeDeleteHooks = append(monstersLevelUpMissionBeforeDeleteHooks, monstersLevelUpMissionHook)
	case boil.AfterDeleteHook:
		monstersLevelUpMissionAfterDeleteHooks = append(monstersLevelUpMissionAfterDeleteHooks, monstersLevelUpMissionHook)
	case boil.BeforeUpsertHook:
		monstersLevelUpMissionBeforeUpsertHooks = append(monstersLevelUpMissionBeforeUpsertHooks, monstersLevelUpMissionHook)
	case boil.AfterUpsertHook:
		monstersLevelUpMissionAfterUpsertHooks = append(monstersLevelUpMissionAfterUpsertHooks, monstersLevelUpMissionHook)
	}
}

// One returns a single monstersLevelUpMission record from the query.
func (q monstersLevelUpMissionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MonstersLevelUpMission, error) {
	o := &MonstersLevelUpMission{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for monsters_level_up_missions")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MonstersLevelUpMission records from the query.
func (q monstersLevelUpMissionQuery) All(ctx context.Context, exec boil.ContextExecutor) (MonstersLevelUpMissionSlice, error) {
	var o []*MonstersLevelUpMission

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MonstersLevelUpMission slice")
	}

	if len(monstersLevelUpMissionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MonstersLevelUpMission records in the query.
func (q monstersLevelUpMissionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count monsters_level_up_missions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q monstersLevelUpMissionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if monsters_level_up_missions exists")
	}

	return count > 0, nil
}

// Mission pointed to by the foreign key.
func (o *MonstersLevelUpMission) Mission(mods ...qm.QueryMod) missionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MissionID),
	}

	queryMods = append(queryMods, mods...)

	return Missions(queryMods...)
}

// LoadMission allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (monstersLevelUpMissionL) LoadMission(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMonstersLevelUpMission interface{}, mods queries.Applicator) error {
	var slice []*MonstersLevelUpMission
	var object *MonstersLevelUpMission

	if singular {
		var ok bool
		object, ok = maybeMonstersLevelUpMission.(*MonstersLevelUpMission)
		if !ok {
			object = new(MonstersLevelUpMission)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMonstersLevelUpMission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMonstersLevelUpMission))
			}
		}
	} else {
		s, ok := maybeMonstersLevelUpMission.(*[]*MonstersLevelUpMission)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMonstersLevelUpMission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMonstersLevelUpMission))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &monstersLevelUpMissionR{}
		}
		args = append(args, object.MissionID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &monstersLevelUpMissionR{}
			}

			for _, a := range args {
				if a == obj.MissionID {
					continue Outer
				}
			}

			args = append(args, obj.MissionID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`missions`),
		qm.WhereIn(`missions.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Mission")
	}

	var resultSlice []*Mission
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Mission")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for missions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for missions")
	}

	if len(missionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Mission = foreign
		if foreign.R == nil {
			foreign.R = &missionR{}
		}
		foreign.R.MonstersLevelUpMission = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.MissionID == foreign.ID {
				local.R.Mission = foreign
				if foreign.R == nil {
					foreign.R = &missionR{}
				}
				foreign.R.MonstersLevelUpMission = local
				break
			}
		}
	}

	return nil
}

// SetMission of the monstersLevelUpMission to the related item.
// Sets o.R.Mission to related.
// Adds o to related.R.MonstersLevelUpMission.
func (o *MonstersLevelUpMission) SetMission(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Mission) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"monsters_level_up_missions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"mission_id"}),
		strmangle.WhereClause("\"", "\"", 2, monstersLevelUpMissionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.MissionID = related.ID
	if o.R == nil {
		o.R = &monstersLevelUpMissionR{
			Mission: related,
		}
	} else {
		o.R.Mission = related
	}

	if related.R == nil {
		related.R = &missionR{
			MonstersLevelUpMission: o,
		}
	} else {
		related.R.MonstersLevelUpMission = o
	}

	return nil
}

// MonstersLevelUpMissions retrieves all the records using an executor.
func MonstersLevelUpMissions(mods ...qm.QueryMod) monstersLevelUpMissionQuery {
	mods = append(mods, qm.From("\"monsters_level_up_missions\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"monsters_level_up_missions\".*"})
	}

	return monstersLevelUpMissionQuery{q}
}

// FindMonstersLevelUpMission retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMonstersLevelUpMission(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*MonstersLevelUpMission, error) {
	monstersLevelUpMissionObj := &MonstersLevelUpMission{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"monsters_level_up_missions\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, monstersLevelUpMissionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from monsters_level_up_missions")
	}

	if err = monstersLevelUpMissionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return monstersLevelUpMissionObj, err
	}

	return monstersLevelUpMissionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MonstersLevelUpMission) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no monsters_level_up_missions provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(monstersLevelUpMissionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	monstersLevelUpMissionInsertCacheMut.RLock()
	cache, cached := monstersLevelUpMissionInsertCache[key]
	monstersLevelUpMissionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			monstersLevelUpMissionAllColumns,
			monstersLevelUpMissionColumnsWithDefault,
			monstersLevelUpMissionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(monstersLevelUpMissionType, monstersLevelUpMissionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(monstersLevelUpMissionType, monstersLevelUpMissionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"monsters_level_up_missions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"monsters_level_up_missions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into monsters_level_up_missions")
	}

	if !cached {
		monstersLevelUpMissionInsertCacheMut.Lock()
		monstersLevelUpMissionInsertCache[key] = cache
		monstersLevelUpMissionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MonstersLevelUpMission.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MonstersLevelUpMission) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	monstersLevelUpMissionUpdateCacheMut.RLock()
	cache, cached := monstersLevelUpMissionUpdateCache[key]
	monstersLevelUpMissionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			monstersLevelUpMissionAllColumns,
			monstersLevelUpMissionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update monsters_level_up_missions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"monsters_level_up_missions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, monstersLevelUpMissionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(monstersLevelUpMissionType, monstersLevelUpMissionMapping, append(wl, monstersLevelUpMissionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update monsters_level_up_missions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for monsters_level_up_missions")
	}

	if !cached {
		monstersLevelUpMissionUpdateCacheMut.Lock()
		monstersLevelUpMissionUpdateCache[key] = cache
		monstersLevelUpMissionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q monstersLevelUpMissionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for monsters_level_up_missions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for monsters_level_up_missions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MonstersLevelUpMissionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), monstersLevelUpMissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"monsters_level_up_missions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, monstersLevelUpMissionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in monstersLevelUpMission slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all monstersLevelUpMission")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MonstersLevelUpMission) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no monsters_level_up_missions provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(monstersLevelUpMissionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	monstersLevelUpMissionUpsertCacheMut.RLock()
	cache, cached := monstersLevelUpMissionUpsertCache[key]
	monstersLevelUpMissionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			monstersLevelUpMissionAllColumns,
			monstersLevelUpMissionColumnsWithDefault,
			monstersLevelUpMissionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			monstersLevelUpMissionAllColumns,
			monstersLevelUpMissionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert monsters_level_up_missions, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(monstersLevelUpMissionPrimaryKeyColumns))
			copy(conflict, monstersLevelUpMissionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"monsters_level_up_missions\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(monstersLevelUpMissionType, monstersLevelUpMissionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(monstersLevelUpMissionType, monstersLevelUpMissionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert monsters_level_up_missions")
	}

	if !cached {
		monstersLevelUpMissionUpsertCacheMut.Lock()
		monstersLevelUpMissionUpsertCache[key] = cache
		monstersLevelUpMissionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MonstersLevelUpMission record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MonstersLevelUpMission) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MonstersLevelUpMission provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), monstersLevelUpMissionPrimaryKeyMapping)
	sql := "DELETE FROM \"monsters_level_up_missions\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from monsters_level_up_missions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for monsters_level_up_missions")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q monstersLevelUpMissionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no monstersLevelUpMissionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from monsters_level_up_missions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for monsters_level_up_missions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MonstersLevelUpMissionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(monstersLevelUpMissionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), monstersLevelUpMissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"monsters_level_up_missions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, monstersLevelUpMissionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from monstersLevelUpMission slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for monsters_level_up_missions")
	}

	if len(monstersLevelUpMissionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MonstersLevelUpMission) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMonstersLevelUpMission(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MonstersLevelUpMissionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MonstersLevelUpMissionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), monstersLevelUpMissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"monsters_level_up_missions\".* FROM \"monsters_level_up_missions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, monstersLevelUpMissionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MonstersLevelUpMissionSlice")
	}

	*o = slice

	return nil
}

// MonstersLevelUpMissionExists checks if the MonstersLevelUpMission row exists.
func MonstersLevelUpMissionExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"monsters_level_up_missions\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if monsters_level_up_missions exists")
	}

	return exists, nil
}

// Exists checks if the MonstersLevelUpMission row exists.
func (o *MonstersLevelUpMission) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MonstersLevelUpMissionExists(ctx, exec, o.ID)
}
