// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UserMonster is an object representing the database table.
type UserMonster struct {
	ID int64 `boil:"id" json:"id" toml:"id" yaml:"id"`
	// ユーザーID
	UserID int64 `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	// モンスターID
	MonsterID int64     `boil:"monster_id" json:"monster_id" toml:"monster_id" yaml:"monster_id"`
	Level     int       `boil:"level" json:"level" toml:"level" yaml:"level"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *userMonsterR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userMonsterL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserMonsterColumns = struct {
	ID        string
	UserID    string
	MonsterID string
	Level     string
	UpdatedAt string
	CreatedAt string
}{
	ID:        "id",
	UserID:    "user_id",
	MonsterID: "monster_id",
	Level:     "level",
	UpdatedAt: "updated_at",
	CreatedAt: "created_at",
}

var UserMonsterTableColumns = struct {
	ID        string
	UserID    string
	MonsterID string
	Level     string
	UpdatedAt string
	CreatedAt string
}{
	ID:        "user_monsters.id",
	UserID:    "user_monsters.user_id",
	MonsterID: "user_monsters.monster_id",
	Level:     "user_monsters.level",
	UpdatedAt: "user_monsters.updated_at",
	CreatedAt: "user_monsters.created_at",
}

// Generated where

var UserMonsterWhere = struct {
	ID        whereHelperint64
	UserID    whereHelperint64
	MonsterID whereHelperint64
	Level     whereHelperint
	UpdatedAt whereHelpertime_Time
	CreatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "\"user_monsters\".\"id\""},
	UserID:    whereHelperint64{field: "\"user_monsters\".\"user_id\""},
	MonsterID: whereHelperint64{field: "\"user_monsters\".\"monster_id\""},
	Level:     whereHelperint{field: "\"user_monsters\".\"level\""},
	UpdatedAt: whereHelpertime_Time{field: "\"user_monsters\".\"updated_at\""},
	CreatedAt: whereHelpertime_Time{field: "\"user_monsters\".\"created_at\""},
}

// UserMonsterRels is where relationship names are stored.
var UserMonsterRels = struct {
	Monster string
	User    string
}{
	Monster: "Monster",
	User:    "User",
}

// userMonsterR is where relationships are stored.
type userMonsterR struct {
	Monster *Monster `boil:"Monster" json:"Monster" toml:"Monster" yaml:"Monster"`
	User    *User    `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userMonsterR) NewStruct() *userMonsterR {
	return &userMonsterR{}
}

func (r *userMonsterR) GetMonster() *Monster {
	if r == nil {
		return nil
	}
	return r.Monster
}

func (r *userMonsterR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// userMonsterL is where Load methods for each relationship are stored.
type userMonsterL struct{}

var (
	userMonsterAllColumns            = []string{"id", "user_id", "monster_id", "level", "updated_at", "created_at"}
	userMonsterColumnsWithoutDefault = []string{"user_id", "monster_id", "level"}
	userMonsterColumnsWithDefault    = []string{"id", "updated_at", "created_at"}
	userMonsterPrimaryKeyColumns     = []string{"id"}
	userMonsterGeneratedColumns      = []string{}
)

type (
	// UserMonsterSlice is an alias for a slice of pointers to UserMonster.
	// This should almost always be used instead of []UserMonster.
	UserMonsterSlice []*UserMonster
	// UserMonsterHook is the signature for custom UserMonster hook methods
	UserMonsterHook func(context.Context, boil.ContextExecutor, *UserMonster) error

	userMonsterQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userMonsterType                 = reflect.TypeOf(&UserMonster{})
	userMonsterMapping              = queries.MakeStructMapping(userMonsterType)
	userMonsterPrimaryKeyMapping, _ = queries.BindMapping(userMonsterType, userMonsterMapping, userMonsterPrimaryKeyColumns)
	userMonsterInsertCacheMut       sync.RWMutex
	userMonsterInsertCache          = make(map[string]insertCache)
	userMonsterUpdateCacheMut       sync.RWMutex
	userMonsterUpdateCache          = make(map[string]updateCache)
	userMonsterUpsertCacheMut       sync.RWMutex
	userMonsterUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userMonsterAfterSelectHooks []UserMonsterHook

var userMonsterBeforeInsertHooks []UserMonsterHook
var userMonsterAfterInsertHooks []UserMonsterHook

var userMonsterBeforeUpdateHooks []UserMonsterHook
var userMonsterAfterUpdateHooks []UserMonsterHook

var userMonsterBeforeDeleteHooks []UserMonsterHook
var userMonsterAfterDeleteHooks []UserMonsterHook

var userMonsterBeforeUpsertHooks []UserMonsterHook
var userMonsterAfterUpsertHooks []UserMonsterHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserMonster) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMonsterAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserMonster) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMonsterBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserMonster) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMonsterAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserMonster) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMonsterBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserMonster) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMonsterAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserMonster) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMonsterBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserMonster) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMonsterAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserMonster) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMonsterBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserMonster) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMonsterAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserMonsterHook registers your hook function for all future operations.
func AddUserMonsterHook(hookPoint boil.HookPoint, userMonsterHook UserMonsterHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userMonsterAfterSelectHooks = append(userMonsterAfterSelectHooks, userMonsterHook)
	case boil.BeforeInsertHook:
		userMonsterBeforeInsertHooks = append(userMonsterBeforeInsertHooks, userMonsterHook)
	case boil.AfterInsertHook:
		userMonsterAfterInsertHooks = append(userMonsterAfterInsertHooks, userMonsterHook)
	case boil.BeforeUpdateHook:
		userMonsterBeforeUpdateHooks = append(userMonsterBeforeUpdateHooks, userMonsterHook)
	case boil.AfterUpdateHook:
		userMonsterAfterUpdateHooks = append(userMonsterAfterUpdateHooks, userMonsterHook)
	case boil.BeforeDeleteHook:
		userMonsterBeforeDeleteHooks = append(userMonsterBeforeDeleteHooks, userMonsterHook)
	case boil.AfterDeleteHook:
		userMonsterAfterDeleteHooks = append(userMonsterAfterDeleteHooks, userMonsterHook)
	case boil.BeforeUpsertHook:
		userMonsterBeforeUpsertHooks = append(userMonsterBeforeUpsertHooks, userMonsterHook)
	case boil.AfterUpsertHook:
		userMonsterAfterUpsertHooks = append(userMonsterAfterUpsertHooks, userMonsterHook)
	}
}

// One returns a single userMonster record from the query.
func (q userMonsterQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserMonster, error) {
	o := &UserMonster{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for user_monsters")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserMonster records from the query.
func (q userMonsterQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserMonsterSlice, error) {
	var o []*UserMonster

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserMonster slice")
	}

	if len(userMonsterAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserMonster records in the query.
func (q userMonsterQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count user_monsters rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userMonsterQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if user_monsters exists")
	}

	return count > 0, nil
}

// Monster pointed to by the foreign key.
func (o *UserMonster) Monster(mods ...qm.QueryMod) monsterQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MonsterID),
	}

	queryMods = append(queryMods, mods...)

	return Monsters(queryMods...)
}

// User pointed to by the foreign key.
func (o *UserMonster) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadMonster allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userMonsterL) LoadMonster(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserMonster interface{}, mods queries.Applicator) error {
	var slice []*UserMonster
	var object *UserMonster

	if singular {
		var ok bool
		object, ok = maybeUserMonster.(*UserMonster)
		if !ok {
			object = new(UserMonster)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserMonster)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserMonster))
			}
		}
	} else {
		s, ok := maybeUserMonster.(*[]*UserMonster)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserMonster)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserMonster))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userMonsterR{}
		}
		args = append(args, object.MonsterID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userMonsterR{}
			}

			for _, a := range args {
				if a == obj.MonsterID {
					continue Outer
				}
			}

			args = append(args, obj.MonsterID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`monsters`),
		qm.WhereIn(`monsters.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Monster")
	}

	var resultSlice []*Monster
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Monster")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for monsters")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for monsters")
	}

	if len(monsterAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Monster = foreign
		if foreign.R == nil {
			foreign.R = &monsterR{}
		}
		foreign.R.UserMonsters = append(foreign.R.UserMonsters, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.MonsterID == foreign.ID {
				local.R.Monster = foreign
				if foreign.R == nil {
					foreign.R = &monsterR{}
				}
				foreign.R.UserMonsters = append(foreign.R.UserMonsters, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userMonsterL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserMonster interface{}, mods queries.Applicator) error {
	var slice []*UserMonster
	var object *UserMonster

	if singular {
		var ok bool
		object, ok = maybeUserMonster.(*UserMonster)
		if !ok {
			object = new(UserMonster)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserMonster)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserMonster))
			}
		}
	} else {
		s, ok := maybeUserMonster.(*[]*UserMonster)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserMonster)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserMonster))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userMonsterR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userMonsterR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserMonsters = append(foreign.R.UserMonsters, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserMonsters = append(foreign.R.UserMonsters, local)
				break
			}
		}
	}

	return nil
}

// SetMonster of the userMonster to the related item.
// Sets o.R.Monster to related.
// Adds o to related.R.UserMonsters.
func (o *UserMonster) SetMonster(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Monster) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_monsters\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"monster_id"}),
		strmangle.WhereClause("\"", "\"", 2, userMonsterPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.MonsterID = related.ID
	if o.R == nil {
		o.R = &userMonsterR{
			Monster: related,
		}
	} else {
		o.R.Monster = related
	}

	if related.R == nil {
		related.R = &monsterR{
			UserMonsters: UserMonsterSlice{o},
		}
	} else {
		related.R.UserMonsters = append(related.R.UserMonsters, o)
	}

	return nil
}

// SetUser of the userMonster to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserMonsters.
func (o *UserMonster) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_monsters\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userMonsterPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userMonsterR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserMonsters: UserMonsterSlice{o},
		}
	} else {
		related.R.UserMonsters = append(related.R.UserMonsters, o)
	}

	return nil
}

// UserMonsters retrieves all the records using an executor.
func UserMonsters(mods ...qm.QueryMod) userMonsterQuery {
	mods = append(mods, qm.From("\"user_monsters\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_monsters\".*"})
	}

	return userMonsterQuery{q}
}

// FindUserMonster retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserMonster(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*UserMonster, error) {
	userMonsterObj := &UserMonster{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_monsters\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userMonsterObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from user_monsters")
	}

	if err = userMonsterObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userMonsterObj, err
	}

	return userMonsterObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserMonster) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_monsters provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userMonsterColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userMonsterInsertCacheMut.RLock()
	cache, cached := userMonsterInsertCache[key]
	userMonsterInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userMonsterAllColumns,
			userMonsterColumnsWithDefault,
			userMonsterColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userMonsterType, userMonsterMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userMonsterType, userMonsterMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_monsters\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_monsters\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into user_monsters")
	}

	if !cached {
		userMonsterInsertCacheMut.Lock()
		userMonsterInsertCache[key] = cache
		userMonsterInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserMonster.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserMonster) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userMonsterUpdateCacheMut.RLock()
	cache, cached := userMonsterUpdateCache[key]
	userMonsterUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userMonsterAllColumns,
			userMonsterPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update user_monsters, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_monsters\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userMonsterPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userMonsterType, userMonsterMapping, append(wl, userMonsterPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update user_monsters row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for user_monsters")
	}

	if !cached {
		userMonsterUpdateCacheMut.Lock()
		userMonsterUpdateCache[key] = cache
		userMonsterUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userMonsterQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for user_monsters")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for user_monsters")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserMonsterSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMonsterPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_monsters\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userMonsterPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in userMonster slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all userMonster")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserMonster) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_monsters provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userMonsterColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userMonsterUpsertCacheMut.RLock()
	cache, cached := userMonsterUpsertCache[key]
	userMonsterUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			userMonsterAllColumns,
			userMonsterColumnsWithDefault,
			userMonsterColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userMonsterAllColumns,
			userMonsterPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert user_monsters, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userMonsterPrimaryKeyColumns))
			copy(conflict, userMonsterPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_monsters\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userMonsterType, userMonsterMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userMonsterType, userMonsterMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert user_monsters")
	}

	if !cached {
		userMonsterUpsertCacheMut.Lock()
		userMonsterUpsertCache[key] = cache
		userMonsterUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserMonster record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserMonster) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UserMonster provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userMonsterPrimaryKeyMapping)
	sql := "DELETE FROM \"user_monsters\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from user_monsters")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for user_monsters")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userMonsterQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no userMonsterQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from user_monsters")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_monsters")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserMonsterSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userMonsterBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMonsterPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_monsters\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userMonsterPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userMonster slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_monsters")
	}

	if len(userMonsterAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserMonster) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserMonster(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserMonsterSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserMonsterSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMonsterPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_monsters\".* FROM \"user_monsters\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userMonsterPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserMonsterSlice")
	}

	*o = slice

	return nil
}

// UserMonsterExists checks if the UserMonster row exists.
func UserMonsterExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_monsters\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if user_monsters exists")
	}

	return exists, nil
}

// Exists checks if the UserMonster row exists.
func (o *UserMonster) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserMonsterExists(ctx, exec, o.ID)
}
